[1] login feature
zinza-d2-training/trungnq-php pull request #16
Opened 2022-06-03 08:24 UTC by trungnq-zinza

2022-06-06 03:24 UTC, phuongcm-zinza requested changes

2022-06-06 03:24 UTC, phuongcm-zinza commented on resources/views/layouts/client.blade.php
> +    <div class="wrapper mx-auto flex flex-col min-h-screen" style="max-width: 1440px ">
ko nên viết style inline như này nhé

2022-06-06 03:51 UTC, trungnq-zinza commented on app/Http/Controllers/Authen/AuthenController.php
> +    public function post_login(LoginRequest $request )
done

2022-06-06 03:51 UTC, trungnq-zinza commented on app/Http/Controllers/Authen/AuthenController.php
> +    public function reset_pass()
done

2022-06-06 03:51 UTC, trungnq-zinza commented on app/Http/Middleware/VerifyLogin.php
> +        else return redirect()->route('custom-login');
done

2022-06-06 03:52 UTC, trungnq-zinza commented on app/Repositories/UserRepository.php
> +class UserRepository {
Done, bỏ đi tầng Repository.

2022-06-06 03:52 UTC, trungnq-zinza commented on app/Repositories/UserRepository.php
> +    }
done

2022-06-06 03:53 UTC, trungnq-zinza commented on resources/sass/app.scss
> +}
done. Em không dùng scss nữa.

2022-06-06 03:53 UTC, trungnq-zinza commented on resources/views/authen/login.blade.php
> +                    <form action="{{route("custom-post-login")}}" class="px-6" method="POST">
done

2022-06-06 04:11 UTC, trungnq-zinza commented on resources/views/authen/login.blade.php
> +</html>
done

2022-06-06 04:11 UTC, trungnq-zinza commented on resources/views/components/dropdown.blade.php
> +        break;
done

2022-06-06 04:11 UTC, trungnq-zinza commented on resources/views/layouts/client.blade.php
> +    <div class="wrapper mx-auto flex flex-col min-h-screen" style="max-width: 1440px ">
done

2022-06-07 09:54 UTC, trungnq-zinza commented on app/Repositories/UserRepository.php
> +        else  return $res = ['error' => 'Email bạn nhập không chính xác'];
em đã sửa lại , hôm qua không để ý git nó ẩn mất mấy cái comment của anh nên em không biết để sửa lại ạ

2022-06-07 09:55 UTC, trungnq-zinza commented on app/Repositories/UserRepository.php
> +        else return false;
em sửa lại rồi.

2022-06-07 10:06 UTC, trungnq-zinza commented on config/app.php
> +    'debug' => (bool) env('APP_DEBUG', true),
ok a

2022-06-07 10:06 UTC, trungnq-zinza commented on database/seeders/users.php
> +        ],[
vâng a

2022-06-08 02:00 UTC, closed without merging