User setting
zinza-d2-training/trungnq-php pull request #17
Opened 2022-06-06 10:15 UTC by trungnq-zinza

2022-06-06 11:20 UTC, phuongcm-zinza requested changes

2022-06-06 11:20 UTC, phuongcm-zinza commented on app/Services/UploadImage.php
> +       public function deletefile($path,$filename){
sao không nối path. filename rồi truyền vào 1 biến thôi

2022-06-06 11:20 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +                ];
Nên throw ra exception rồi bắt phía controller để response

2022-06-06 11:20 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +            $res = new UploadImage();
nên inject Service vào contruct để sử dụng nhiều chỗ.

2022-06-06 11:20 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +        ];
Update xong thì return true thôi message thì xử lý phía controller

2022-06-06 11:20 UTC, phuongcm-zinza commented on config/app.php
> +    'debug' => (bool) env('APP_DEBUG', true),
PHần này sử dụng env, khi cần chỉnh sửa thì sửa trong file .env không sửa trực tiếp trong config

2022-06-06 11:20 UTC, phuongcm-zinza commented on public/js/main.js
> +toast("","");
Đoạn này đang test ah

2022-06-06 11:20 UTC, phuongcm-zinza commented on public/js/main.js
> +    });
Tại sao lại phải dùng ajax để update user cho phức tạp vậy, nếu form đơn giản có thể sử dụng form submit được

2022-06-06 11:20 UTC, phuongcm-zinza commented on resources/views/authen/resetpassword.blade.php
> +    <title>{{$title}}</title>
$title này ko nên truyền từ controller mà nên sử dụng localization của laravel
https://laravel.com/docs/6.x/localization

2022-06-06 11:20 UTC, phuongcm-zinza commented on routes/web.php
> +});
thiếu dòng trống cuối file, check lại các file php tương tự

2022-06-07 06:16 UTC, trungnq-zinza commented on app/Services/UserService.php
> +        return $user->fresh();
observer là mình tạo thêm 1 cái dạng class để CRUD model ạ, vậy thì khi sử dụng sẽ khởi tạo nó trong contruct của service ạ.

2022-06-08 01:15 UTC, trungnq-zinza commented on app/Http/Controllers/Authen/AuthenController.php
> +    }
xong ạ

2022-06-08 01:15 UTC, trungnq-zinza commented on app/Http/Middleware/VerifyLogin.php
> +        }
xongg a

2022-06-08 01:16 UTC, trungnq-zinza commented on app/Services/UserService.php
> +        else  return $res = ['error' => 'Email bạn nhập không chính xác'];
xong ạ.

2022-06-08 01:16 UTC, trungnq-zinza commented on app/Services/UserService.php
> +        else return false;
done

2022-06-08 01:16 UTC, trungnq-zinza commented on app/Http/Controllers/Authen/AuthenController.php
> +        dd($data);
ok a

2022-06-08 01:18 UTC, trungnq-zinza commented on config/app.php
> +    'debug' => (bool) env('APP_DEBUG', true),
xong ạ

2022-06-08 01:19 UTC, trungnq-zinza commented on routes/web.php
> +});
ok a

2022-06-08 01:22 UTC, trungnq-zinza commented on app/Services/UserService.php
> +        return User::where('id',$id)->first();
xong ạ

2022-06-08 01:23 UTC, trungnq-zinza commented on app/Services/UploadImage.php
> +              $file_name = time().'-avatar.'.$file->extension();
xong ạ

2022-06-08 08:48 UTC, phuongcm-zinza commented on app/Observers/AccountObserver.php
> +    } */
chỗ nào ko dùng thì xóa đi

2022-06-08 08:49 UTC, phuongcm-zinza commented on app/Services/UploadImage.php
>                }
Chú ý format code

2022-06-08 08:51 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +        return User::findOrFail(Auth::id());
Truyền id vào mà sao lại lấy Auth::id()

2022-06-08 08:51 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +        return User::findOrFail(Auth::id());
Truyền id vào mà sao lại lấy Auth::id()

2022-06-08 08:51 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +        return User::findOrFail(Auth::id());
Truyền id vào mà sao lại lấy Auth::id()

2022-06-08 08:53 UTC, phuongcm-zinza commented on app/Services/UserService.php
>          else return false;
ko viết if else kiểu này, viết đầy đủ thẻ đóng mở ra

2022-06-08 08:55 UTC, phuongcm-zinza commented on app/Services/UserService.php
> +        if (!empty($data['old_password']) && !empty($data['password'])) {
đoạn check if empty này check ngoài request rồi thì ko cần check trong này nữa

2022-06-08 09:04 UTC, phuongcm-zinza commented on app/Services/UserService.php
> -        ];
Sửa lại logic đoạn này

2022-06-08 09:08 UTC, phuongcm-zinza commented on public/js/main.js
> +    }
ko có type default ah

2022-06-08 09:08 UTC, phuongcm-zinza commented on public/js/main.js
> +    }
ko có type default ah

2022-06-08 09:09 UTC, phuongcm-zinza commented on public/js/main.js
> -toast("","");
cái này có sử dụng ko, ko dùng thì xóa đi

2022-06-08 09:12 UTC, phuongcm-zinza commented on resources/views/pages/account.blade.php
> +                    <input class="border-slate-300 rounded-lg w-80 " type="text" name="dob" id="dob" :value="$user - > dob">
xem lại $user - > dob

2022-06-09 06:24 UTC, merged